accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

from .views import PasswordsChangeView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.MyRegisterFormView.as_view(), name='register'),
    path('<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('login/', views.user_login, name='login'),
    path("logout/", views.logout, name="logout"),
    path('edit_profile/', views.UserEditFormView.as_view(), name='edit_profile'),
    #path('password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password.html')),
    path('password/', PasswordsChangeView.as_view(template_name='accounts/password.html')),
    path('password_success', views.password_success, name='password_success'),
    path('<int:pk>/profile/', views.UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit_profile_page', views.EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page', views.CreateProfilePageView.as_view(), name='create_profile_page'),
]

blog/urls.py
from django.urls import path

from . import views
from .views import CategoryView, CategoryListView, LikeView, ArticleDetailView

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.DeletePostView.as_view(), name='delete_post'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('category-list/', CategoryListView, name='category-list'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('<int:pk>/comment', views.AddCommentView.as_view(), name='comment_new'),

]

mysite1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.conf import settings
from django.db import models
import datetime
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('blog:add_category')


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to='images/profile')
    website_url = models.CharField(max_length=255, null=True, blank=True,)
    facebook_url = models.CharField(max_length=255, null=True, blank=True,)
    twitter_url = models.CharField(max_length=255, null=True, blank=True,)
    instagram_url = models.CharField(max_length=255, null=True, blank=True,)
    pinterest_url = models.CharField(max_length=255, null=True, blank=True,)


    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse ('blog:index')

class Post(models.Model):
    post_title = models.CharField(max_length=100)
    header_image = models.ImageField(null=True, blank=True, upload_to='images')
    post_body = RichTextField(blank=True, null=True)
    pub_date = models.DateTimeField('date published')
    post_author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='post_author')
    category = models.CharField(max_length=100, default='uncategorized')
    snippet = models.CharField(max_length=100)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return str(self.post_title)+' | ' + str(self.post_author)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Comment(models.Model):
    post = models.ForeignKey(Post,  related_name='comments', on_delete=models.CASCADE)
    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='name')
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.post_title, self.name)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from blog.models import Profile


class ProfilePageForm(forms.ModelForm):
    class Meta:

        model = Profile
        fields = ('bio', 'profile_pic', 'website_url', 'facebook_url', 'twitter_url', 'instagram_url', 'pinterest_url')
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add some text'}),
               # 'profile_pic': forms.Select(attrs={'class': 'form-control'}),
                'website_url': forms.TextInput(attrs={'class': 'form-control'}),
                'facebook_url': forms.TextInput(attrs={'class': 'form-control'}),
                'twitter_url': forms.TextInput(attrs={'class': 'form-control'}),
                'instagram_url': forms.TextInput(attrs={'class': 'form-control'}),
                'pinterest_url': forms.TextInput(attrs={'class': 'form-control'}),

        }


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


def logout(request):
    logout(request)


class EditProfileForm(UserChangeForm):
    email = forms.EmailField(max_length=200, help_text='Required',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_login = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_staff = forms.CharField(max_length=100, widget=forms.CheckboxInput(attrs={'class': 'form-check'}))
    is_active = forms.CharField(max_length=100, widget=forms.CheckboxInput(attrs={'class': 'form-check'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password','last_login', 'is_staff', 'is_active')


class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=200, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.views.generic.edit import FormView, CreateView
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import LoginForm, SignUpForm, EditProfileForm, PasswordChangingForm
from django.contrib import auth
from django.contrib.auth.forms import PasswordChangeForm
from blog.models import Profile
from .forms import ProfilePageForm


from blog.models import Post

from django.contrib.auth.decorators import login_required


class MyRegisterFormView(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:login')
    template_name = "accounts/register.html"

    def form_valid(self, form):
        form.save()
        # Функция super( тип [ , объект или тип ] )
        # Возвратите объект прокси, который делегирует вызовы метода родительскому или родственному классу типа .
        return super(MyRegisterFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(MyRegisterFormView, self).form_invalid(form)


class UserProfileView(generic.DetailView):
    model = User
    template_name = 'accounts/profile.html'
    

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'accounts/profile.html')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout(request):
    auth.logout(request)
    return render(request,'accounts/logout.html')


class UserEditFormView(generic.UpdateView):
    form_class = EditProfileForm
    success_url = reverse_lazy('blog:index')
    template_name = "accounts/edit_profile.html"

    def get_object(self):
        return self.request.user


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url = reverse_lazy('accounts:password_success')


def password_success(request):
    return render(request, 'accounts/password_success.html', {})


class EditProfilePageView(generic.UpdateView):
    model = Profile
    template_name = 'accounts/edit_profile_page.html'
    success_url = reverse_lazy('blog:index')
    fields=['bio', 'profile_pic', 'website_url', 'facebook_url', 'twitter_url', 'instagram_url', 'pinterest_url',]


class CreateProfilePageView(CreateView):
    model = Profile
    form_class = ProfilePageForm
    template_name = 'accounts/create_profile_page.html'



    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

accounts/templates/accounts/create_profile_page.html
{% extends 'blog/base.html' %}
{% block title %}Edit profile page{% endblock %}
{% block main_content %}

{% if user.is_authenticated %}
        <h1>Edit profile page</h1>
        <form method="POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}
            <button class="btn btn-secondary">Save</button>
        </form>
{% else %}
    <h>Error</h>

{% endif %}
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'blog/base.html' %}

{% block main_content %}

{% block title %}Settings{% endblock %}

<h1>Settings</h1>


<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update profile">
</form>



{% endblock %}

accounts/templates/accounts/edit_profile_page.html
{% extends 'blog/base.html' %}
{% block title %}Edit profile page{% endblock %}
{% block main_content %}

{% if user.is_authenticated %}
    {% if user.id == profile.user.id %}
        <h1>Edit profile page</h1>
        <form method="POST" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}
             <input type="submit" value="Save">
        </form>
    {% else %}
        <h>Error</h>
    {% endif %}
{% endif %}
{% endblock %}

accounts/templates/accounts/footer.html
<footer class="container">
  <p>&copy; Company 2017-2020</p>
</footer>

accounts/templates/accounts/login.html
{% extends "blog/base.html" %}
{% block title %}Log in{% endblock %}
{% block main_content %}
    <h1>Log in</h1>
    <p>Please, use the following form to log in:</p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log in"></p>
    </form>
    <a href="{% url 'accounts:register'%}">Create a new account</a>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "blog/base.html"  %}

{% block main_content %}

    <div class="content">
        <div class="section-inner clearfix">

        <p>You are logged out. <a href="{% url 'accounts:login' %}">Click here</a> to login again.</p>

        </div>
    </div>

{% endblock %}

accounts/templates/accounts/password.html
{% extends "blog/base.html" %}
{% block title %}Change Password{% endblock %}
{% block main_content %}
    <h1>Change password</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Save"></p>
    </form>
    <ul>
        <li>Your password can’t be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can’t be a commonly used password.</li>
        <li>Your password can’t be entirely numeric.</li>
    </ul>
{% endblock %}

accounts/templates/accounts/password_success.html
{% extends "blog/base.html" %}
{% block title %}Password Updated Successfully{% endblock %}
{% block main_content %}
<h2>Password Updated Successfully</h2>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}{{ user.username }}{% endblock %}

{% block main_content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>{{ user.username }}</h1>

{% if user.is_authenticated %}
    {% if user == request.user %}
        {%if user.profile %}
            <li><a class="dropdown-item" href="{% url 'accounts:edit_profile_page'  user.profile.id%}">Edit profile page</a></li>
        {% else %}
            <li><a class="dropdown-item" href="{% url 'accounts:create_profile_page' %}">Create profile page</a></li>
        {% endif %}
    {% endif %}
{% endif %}

<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-2">
        {% if user.profile.profile_pic %}
            <img src="{{user.profile.profile_pic.url}}" class="img-fluid rounded-start" alt="...">
        {% else %}
            <img src="{% static 'blog/images/default.png' %}" class="img-fluid rounded-start" alt="...">
        {% endif %}
    </div>
    <div class="col-md-10">
      <div class="card-body">
        <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5>
        <p class="small text-muted">
            {% if user.profile.website_url%}
                <a href="{{user.profile.website_url}}">Website </a>
            {% endif %}
            {% if user.profile.facebook_url%}
                | <a href="{{user.profile.facebook_url}}">Facebook</a>
            {% endif %}
            {% if user.profile.twitter_url%}
               | <a href="{{user.profile.twitter_url}}">Twitter</a>
            {% endif %}
             {% if user.profile.instagram_url%}
               | <a href="{{user.profile.instagram_url}}">Instagram</a>
            {% endif %}
            {% if user.profile.pinterest_url%}
               | <a href="{{user.profile.pinterest_url}}">Pinterest</a>
            {% endif %}
        </p>
        <p class="card-text">{{user.profile.bio}}</p>

      </div>
    </div>
  </div>
</div>

{% if user.is_authenticated %}
    {% if user == request.user %}
        <p>Change profile image</p>
    {% endif %}
{% endif %}

{% if user.is_authenticated %}
    {% if user != request.user %}
        <p>Send a message</p>
    {% endif %}
{% endif %}

{% if user.is_authenticated %}
    {% if user != request.user %}
        <p>Block this user</p>
    {% endif %}
{% endif %}

<p>{{user.first_name}} {{user.last_name}}</p>
<p>Date joined: {{user.date_joined}}</p>
<p>Last login: {{user.last_login}}</p>
<p>Country</p>

<h5>Bio</h5>
<p>{{user.profile.bio}} </p>

<h5>Posts by <strong>{{ user.username }} </strong></h5>

<ul>
{% for post in user.post_set.all %}
    <li><a href="{% url 'blog:detail' pk=post.pk %}">{{ post.post_title }}</a></li>
{% endfor %}
</ul>

<p>View all (number)></p>

<h5>Favorite posts</h5>
<p>Post 1</p>
<p>Post 2</p>
<p>View all (number)></p>

<h5>Answered questions</h5>
<p>Question 1</p>
<p>Question 2</p>
<p>View all (number)></p>

<h5>Friends</h5>
{% if user.is_authenticated %}
    {% if user != request.user %}
        <p>+ Send a friend request</p>
    {% endif %}
{% endif %}
<p>Friend 1</p>
<p>Friend 2</p>
<p>View all (number)></p>


{% endblock %}

accounts/templates/accounts/register.html
{% extends 'blog/base.html' %}

{% block main_content %}

{% block title %}Register{% endblock %}

<h2>Create a new account</h2>


<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>



<a href="{% url 'accounts:login'%}">I already have an account</a>
{% endblock %}