accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

from .views import PasswordsChangeView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.MyRegisterFormView.as_view(), name='register'),
    path('<int:pk>/', views.UserProfileView.as_view(), name='profile'),
    path('login/', views.user_login, name='login'),
    path("logout/", views.logout, name="logout"),
    path('edit_profile/', views.UserEditFormView.as_view(), name='edit_profile'),
    #path('password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password.html')),
    path('password/', PasswordsChangeView.as_view(template_name='accounts/password.html')),
    path('password_success', views.password_success, name='password_success'),
    path('<int:pk>/profile/', views.UserProfileView.as_view(), name='profile'),
    path('<int:pk>/edit_profile_page', views.EditProfilePageView.as_view(), name='edit_profile_page'),
    path('create_profile_page', views.CreateProfilePageView.as_view(), name='create_profile_page'),
]

blog/urls.py
from django.urls import path

from . import views
from .views import CategoryView, CategoryListView, LikeView, ArticleDetailView

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.DeletePostView.as_view(), name='delete_post'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('category-list/', CategoryListView, name='category-list'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('<int:pk>/comment', views.AddCommentView.as_view(), name='comment_new'),

]

mysite1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.conf import settings
from django.db import models
import datetime
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return reverse('blog:add_category')


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(null=True, blank=True, upload_to='images/profile')
    website_url = models.CharField(max_length=255, null=True, blank=True,)
    facebook_url = models.CharField(max_length=255, null=True, blank=True,)
    twitter_url = models.CharField(max_length=255, null=True, blank=True,)
    instagram_url = models.CharField(max_length=255, null=True, blank=True,)
    pinterest_url = models.CharField(max_length=255, null=True, blank=True,)


    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse ('blog:index')

class Post(models.Model):
    post_title = models.CharField(max_length=100)
    header_image = models.ImageField(null=True, blank=True, upload_to='images')
    post_body = RichTextField(blank=True, null=True)
    pub_date = models.DateTimeField('date published')
    post_author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='post_author')
    category = models.CharField(max_length=100, default='uncategorized')
    snippet = models.CharField(max_length=100)
    likes = models.ManyToManyField(User, related_name='blog_posts')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return str(self.post_title)+' | ' + str(self.post_author)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Comment(models.Model):
    post = models.ForeignKey(Post,  related_name='comments', on_delete=models.CASCADE)
    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='name')
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.post_title, self.name)

blog/forms.py
from django import forms

from .models import Post, Category, Comment

choices = Category.objects.all().values_list('category_name', 'category_name')

choice_list=[]

for item in choices:
    choice_list.append(item)


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('post_title', 'category', 'post_body', 'snippet', 'header_image')

        widgets = {
            'post_title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'post_body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add some text'}),
            'snippet': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add some text'}),

        }


class CommentForm(forms.ModelForm):
   
    class Meta:
        model = Comment
        fields = ('body', ) 

        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Add some text'}),
        }

blog/views.py
from django.contrib.auth.models import User
from django.utils import timezone

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from .models import Post, Category, Comment
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, render
from django.views import generic
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.views.generic import DeleteView, CreateView, DetailView


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True

    return HttpResponseRedirect(reverse('blog:detail', args=[str(pk)]))


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        """
        Return the last published posts (not including those set to be
        published in the future).
        """
        return Post.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context['cat_menu'] = cat_menu
        return context


class ArticleDetailView(DetailView):
    template_name = 'blog/detail.html'
    model = Post


    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(ArticleDetailView, self).get_context_data(*args, **kwargs)

        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()

        liked = False
        if stuff.likes.filter(id=self.request.user.id).exists():
            liked=True

        context['cat_menu'] = cat_menu
        context['total_likes'] = total_likes
        context['liked'] = liked
        
        return context


class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment_new.html'

    def form_valid(self, form):
        form.instance.name = self.request.user
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

    def get_success_url(self):

        return reverse_lazy('blog:detail', kwargs={'pk':self.kwargs['pk']})
    



def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.post_author = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_new.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.post_author = request.user
            post.pub_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


class DeletePostView(DeleteView):
    model = Post
    template_name = 'blog/delete_post.html'
    success_url = reverse_lazy('blog:index')


class AddCategoryView(CreateView):
    model = Category
    template_name = 'blog/add_category.html'
    fields = '__all__'


def CategoryView(request, cats):
    category_posts = Post.objects.filter(category=cats.replace('-', ' '))
    return render(request, 'blog/categories.html',
                  {'cats': cats.title().replace('-', ' '), 'category_posts': category_posts})


def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request, 'blog/category_list.html', {'cat_menu_list' : cat_menu_list})

blog/templates/blog/add_category.html
{% extends 'blog/base.html' %}
{% block title %}Add a new category{% endblock %}
{% block main_content %}
    <h1>New category</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
         <input type="submit" value="Save">
    </form>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="/static/blog/css/style.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{% block title %}Blogging website{% endblock %}</title>

</head>
<body>
<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    {% include "blog/navbar.html" %}
    <div class="container"
         {% block main_content %}
         {% endblock %}
    </div>

    {% include "blog/footer.html" %}

</body>
</html>

blog/templates/blog/categories.html
{% extends 'blog/base.html' %}

{% block main_content %}

{% if category_posts %}
    <h1>{{ cats }}</h1>

    <ul>
    {% for post in category_posts %}
        <li>
                <a href="/blog/{{ post.id }}/">{{ post.post_title }} </a> by <a href="{% url 'accounts:profile' pk=post.post_author.pk %}">{{post.post_author}}</a>
                <br/>
                <br/>
                {{ post.post_body|slice:":200"|safe }}
                <br/>
                <br/>
            </li>
    {% endfor %}
    </ul>

{% else %}
<h2>Error. This page does not exist</h2>
{% endif %}


{% endblock %}

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% block title %}Categories{% endblock %}
{% block main_content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>Blog Categories</h1>

{% for item in cat_menu_list %}
    <h4><a href="{% url 'blog:category' item|slugify %}">{{ item }}</a></h4>
{% endfor %}

{% endblock %}

blog/templates/blog/comment_new.html
{% extends 'blog/base.html' %}
{% block title %}Add a comment{% endblock %}
{% block main_content %}
{% if user.is_authenticated %}
    <h1>New comment</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
         <input type="submit" value="Save">
    </form>
{% else %}
    <p>Log in to add a comment</p>
{% endif %}
{% endblock %}

blog/templates/blog/delete_post.html
{% extends 'blog/base.html' %}
{% block title %}Delete post{% endblock %}
{% block main_content %}

<h3>Delete post: {{post.post_title}}</h3>
<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        <strong>Do you want to delete this post?</strong><br/>
        <button class="btn btn-secondary">Delete post</button>
</div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}{{ post.post_title }}{% endblock %}
{% block main_content %}


<h1><strong>{{ post.post_title }}</strong></h1>
<p>{{ post.pub_date }}</p>

{% if user.is_authenticated %}
    {% if post.post_author == request.user %}
        <a href="{% url 'blog:post_edit' pk=post.pk %}">Edit post</a>
        <a href="{% url 'blog:delete_post' pk=post.pk %}">Delete</a>
    {% endif %}
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p><a href="{% url 'blog:category' post.category|slugify%}">{{post.category}}</a></p>

<p> by <a href="{% url 'accounts:profile' pk=post.post_author.pk %}">{{ post.post_author }}</a></p>

{% if post.header_image %}
    <img src='{{ post.header_image.url }}'>
{% endif %}

<br/><br/>
<p>{{ post.post_body| safe }}</p>
<hr>


<form action="{% url 'blog:like_post' post.pk %}"
      method="POST">
    {% csrf_token %}
    {% if user.is_authenticated %}
        {% if liked %}
            <button type="submit", name="post_id", value="{{ post.id }}",
                class="btn btn-danger btn-sm">Unlike</button>
        {% else %}
            <button type="submit", name="post_id", value="{{ post.id }}",
                class="btn btn-primary btn-sm">Like</button>
        {% endif %}

    {% else %}
        <small><a href="{% url 'accounts:login'%}">Login </a>to like</small>
    {% endif %}
    - {{total_likes}} likes
</form>
<br/>
<a href="{% url 'blog:index'%}" class="btn btn-secondary">Back</a>


<br/><br/>
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-2">
        {% if post.post_author.profile.profile_pic %}
            <img src="{{post.post_author.profile.profile_pic.url}}" class="img-fluid rounded-start" alt="...">
        {% else %}
            <img src="{% static 'blog/images/default.png' %}" class="img-fluid rounded-start" alt="...">
        {% endif %}
    </div>
    <div class="col-md-10">
      <div class="card-body">
        <h5 class="card-title">{{post.post_author.first_name}} {{post.post_author.last_name}}</h5>
        <p class="small text-muted">
            {% if post.post_author.profile.website_url%}
                <a href="{{post.post_author.profile.website_url}}">Website </a>
            {% endif %}
            {% if post.post_author.profile.facebook_url%}
                | <a href="{{post.post_author.profile.facebook_url}}">Facebook</a>
            {% endif %}
            {% if post.post_author.profile.twitter_url%}
               | <a href="{{post.post_author.profile.twitter_url}}">Twitter</a>
            {% endif %}
             {% if post.post_author.profile.instagram_url%}
               | <a href="{{post.post_author.profile.instagram_url}}">Instagram</a>
            {% endif %}
            {% if post.post_author.profile.pinterest_url%}
               | <a href="{{post.post_author.profile.pinterest_url}}">Pinterest</a>
            {% endif %}
        </p>
        <p class="card-text">{{post.post_author.profile.bio}}</p>

      </div>
    </div>
  </div>
</div>


{% if not post.comments.all %}
    No comments yet <a href="{% url 'blog:comment_new' post.pk%}">Add one</a>
{% else %}


    <br/>
    <div class="media-list">
        <h2>Comments ({{post.comments.all.count}})</h2>
        <a href="{% url 'blog:comment_new' post.pk%}">Add a comment</a>
        {% for comment in post.comments.all %}
            <div>
                {% if comment.name.profile.profile_pic %}
                    <img src="{{comment.name.profile.profile_pic.url}}" width=70px height=60px alt="...">
                {% else %}
                    <img src="{% static 'blog/images/default.png' %}" width=70px height=60px alt="...">
                {% endif %}
                <strong>{{ comment.name }} -
                    {{comment.date_added}}</strong>
                <br/>
                {{ comment.body }}
                <br/><br/>
            {% endfor %}
            </div>

    </div>    


    <br/><br/>


{% endif %}

{% endblock %}

blog/templates/blog/footer.html
<footer class="container">
  <p>&copy; Company 2017-2020</p>
</footer>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block main_content %}

{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
        <li>
            <h4><a href="/blog/{{ post.id }}/">{{ post.post_title }} </a></h4>
            by <a href="{% url 'accounts:profile' pk=post.post_author.pk %}">{{post.post_author}}</a>
            <p>in <a href="{% url 'blog:category' post.category|slugify%}">{{post.category}}</a></p>

            {{ post.snippet }}
            <br/>
            {% if post.header_image %}
                <img src="{{post.header_image.url}}" class="img-fluid rounded-start" alt="..."  width="300">
            {% endif %}

        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}



{% endblock %}

blog/templates/blog/navbar.html
<header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'blog:index'%}">
                <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24">Blogging website
            </a>
            <a class="navbar-brand" href="{% url 'polls:index'%}">Polls</a>
             <a class='navbar-brand' href="{% url 'blog:post_new' %}">Add new post</a>
             <a class='navbar-brand' href="{% url 'blog:add_category' %}">Add category</a>

            <ul class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Categories
                            </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown1">
                                    {% for item in testname %}
                                         <li><a class="dropdown-item" href="{% url 'blog:category' item|slugify%}">{{item}}</a></li>
                                     {%endfor%}

                                </ul>
                        </li>
                    </li>


                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Profile
                              </a>
                              <ul class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                <li><a class="dropdown-item" href="{% url 'accounts:edit_profile'%}">Settings</a></li>
                                {%if user.profile %}
                                  <li><a class="dropdown-item" href="{% url 'accounts:edit_profile_page'  user.profile.id%}">Edit profile page</a></li>
                                {% else %}
                                    <li><a class="dropdown-item" href="{% url 'accounts:create_profile_page' %}">Create profile page</a></li>
                                 {% endif %}
                                <li><a class="dropdown-item" href="{% url 'accounts:profile' pk=request.user.pk %}">Your profile</a></li>
                                <li><a class='dropdown-item' href="{% url 'accounts:logout'%}">Log out</a></li>

                              </ul>
            </li>



                        {%else%}
                            <a class="navbar-brand" href="{% url 'accounts:login'%}">Login</a>
                            <a class="navbar-brand" href="{% url 'accounts:register'%}">Register</a>
                        {%endif%}
                    </li>


                </ul>
                    <form class="form-inline my-2 my-lg-0">
                      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>

        </nav>

</header>

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block title %}{{ post.post_title }}{% endblock %}
{% block main_content %}
    <h1>Edit post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
         <input type="submit" value="Save">
    </form>
{% endblock %}

blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}
{% block title %}Add new post{% endblock %}
{% block main_content %}
    <h1>New post</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
         <input type="submit" value="Save">
    </form>
{% endblock %}